### ISSUE TITLE
Does it works on websites?

### ISSUE THREAD

**Issue by Er-rchydy** [jaruba/PowderWeb#31]
I visited [website](http://powder.media/embed-test.html) i thought i will find an input where i put magnet url or acestream link and click to play it inside the browser. can this lib do something like that?
the website ask for `Embed token`, where can i find that token to test this ?

**Comment by jaruba** [comment]
You need to download and install Powder Web on your computer, the embed token is in Powder Web's settings page.

After adding the embed token, you will be able to play torrents (and other protocols, if i ever get to publishing the new release) in your browser. But it would still need Powder Web installed in order to work in your browser.

The way it works is that it transcodes on-the-fly to make videos playable in browsers. You could also play in your browser by using Powder Web as a server on a PC. For example, if you want to stream to your browser, you could use Powder Web on a PC to stream to your phone / tablet / etc

Please be mindful that this is just a beta of the software, it still needs a lot more work.

**Comment by Er-rchydy** [comment]
Ok i see. is there a way to make it work on the browser without installing the app on computer? using something like `WebTorrent`

**Comment by jaruba** [comment]
browsers don't play all video types, web torrent adds torrent support to the browser but not video decoding support.

so web torrent works with any torrent that has a video supported by the browser, this narrows it down to mp4 files.

powder web converts videos from any type to browser supported media (usually fragmented mp4, but it also converts to hls for safari) through transcoding / transmuxing.

this conversion cannot be done in the browser (well, it can, but it's too heavy to be practical), so yes, it needs an application installed locally for this

**Comment by Er-rchydy** [comment]
Ok i see, thanks for the explanation
