### ISSUE TITLE
Which node version to use ?

### ISSUE THREAD

**Issue by bombardinotungtung** [jaruba/PowderWeb#37]
I want to compile it for my rpi 0 w.armv6 raspbian.

which node npm and bower version should i use ? i have compiled it with latest lts release but after running i get invalid host header error .

**Comment by jaruba** [comment]
I suspect it might not be a node.js or bower version issue, if the versions are wrong it usually leads to a visible error in the terminal.

I'm guessing the browser gives this error when it tries to load the Powder Web page? What browser are you using? Can you inspect the HTTP Header that you receive from the server and post it here?

**Comment by jaruba** [comment]
any news on this issue?

**Comment by hardcod3dd** [comment]
Browser is firefox .Not yet.Tomorrow i will try to install from start.clean install.hope it works

**Comment by jaruba** [comment]
You should also be aware that i'm planning to use `torrent-thread` for the torrent engine, it's basically the same engine just built into it's own binary:
https://github.com/jaruba/torrent-thread/releases

This is because forking the electron process is costly and creates a critical bug in the torrent engine. This shouldn't be a big issue though, as the engine can also be built for armv6 into a binary with just node.

But when it comes to AceStream / Sopcast, i don't think there's a good chance of finding their binaries for arm versions, so those features will probably be missing on the rpi.

**Comment by jaruba** [comment]
added node and npm versions to readme
