### ISSUE TITLE
Does the whole torrent download on the user pc or the server? Does it get deleted afterwards?

### ISSUE THREAD

**Issue by odmivolsi** [jaruba/PowderWeb#45]

**Comment by jaruba** [comment]
The whole torrent gets downloaded on the server side. As is the case with streaming videos, in order to play the video from a server, it will need to be downloaded (while playing) on the device too (from the server). But the device that is playing will not be downloading torrents, it will download a video (or a transcoded version of the video) to it's temporary folder and delete it on it's own later on.

As for the server, you can delete the torrents yourself after u don't need them anymore, or set a low number of concurrent downloads and set it to delete paused torrents, in which case it will delete the torrents itself as u add new ones.
