### ISSUE TITLE
Do I have to set up a server myself or is there an API that I can use for this?

### ISSUE THREAD

**Issue by odmivolsi** [jaruba/PowderWeb#57]
I cam across a similar repo https://github.com/webtor-io/player-sdk-js where you can either setup your own server or use the existing server of webtor for a fee. Is there a feature in Powder web for this?

And in case i have to setup a server, do the files also get downloaded to my server too? But wouldn't that be an issue if multiple people start streaming simultaneously? This would require a massive hard disk space even if the files get deleted after a day. 

@jaruba what is the best way to implement it

**Comment by jaruba** [comment]
I know the webtor project, if you use their "free API" you will most probably get a lot of unexpected surprises. At the end of the day you cannot play videos (except MP4 with very specific video / audio encodings) in the browser, because the browser itself does not support anything else.

That project does something similar to Powder Web, as in it downloads the files from the torrents on the server side and transcodes them. I'm well accustomed to free resources, and if the webtor project's API isn't already overloaded, it will be sooner or later and you will need to host it yourself.

Powder Web has no such free API, it needs to be self-hosted. It's your choice what you use, but keep in mind that I wouldn't compare the 2 project (Powder Web and webtor). Although they do have similarities, Powder Web is a torrent / acestream / sopcast / youtube-dl / local media (and probably other protocols too in the future) web client and streamer, while webtor is just a torrent streamer. Regarding your worries about disk space and generally resource usage, I think both projects will create the same issues, as both download torrents and both need to transcode them to work on the web.

> This would require a massive hard disk space even if the files get deleted after a day.

I guess it depends how much people watch per day, but as i said before, both these projects have the same resource usage imo. If you want to share this with a lot (hundreds, thousands, etc) of people then you would probably need a lot of disk space, and a lot of resources to transcode for them also. (unless I make the pre-transcode feature, which is already a task i'm planning)

You could test both the projects to see how they fit your need, as I told you before, you can set a very low number of concurrent torrent downloads and set it to delete the torrents once they are auto-paused, but that's the only automated clean up that this project can do for now.

**Comment by jaruba** [comment]
Another thing you should keep in mind is the size of files. If only one person likes watching 4K videos, one video can have tens of GB, which would be hard to store and also transcode. Just one 4K video (although not all, but many) can be the size of tens of 1080p videos.

**Comment by odmivolsi** [comment]
@jaruba Yes this is my concern.  Even if 5 people start viewing 4k videos simultaneously, it will take a huge space on the hard drive. From where should I get a server that can handle this for cheap? Do you have any suggestions?

Apart from the storage concerns, wouldn't it be a legal liability if I am hosting copyrighted material from my server even if it stays on my server for a day.

**Comment by odmivolsi** [comment]
> (unless I make the pre-transcode feature, which is already a task i'm planning)

What is pre-transcode? How will it affect the storage and resource utilisation on my server?

**Comment by jaruba** [comment]
> From where should I get a server that can handle this for cheap? Do you have any suggestions?

There are so many hosting options out there.. I'm not in a position to recommend one in particular. You can check yourserver.se or hostinger.com, they are pretty cheap imo.. but you should definitely do this research yourself too.

Another option is to just use your home computer to host it, get a free SSL certificate from Let's Encrypt and a cheap domain from namecheap.com

> wouldn't it be a legal liability if I am hosting copyrighted material from my server

I can't give legal advice, I'm not a lawyer.

> What is pre-transcode? How will it affect the storage and resource utilisation on my server?

Right now, in order to stream this media to your users, it will do on-the-fly transcoding. This means that it will convert the videos to something that can play in their browser as they watch it. The benefit of this is that it uses less hard disk space, but more resources to transcode per user. The alternative is pre-transcoding, this means that when a download finishes, it starts transcoding it to disk, this in turn will use more storage space, but less resources to stream per user. (as it will serve the data from disk instead of converting it on demand)

I don't think pre-transcoding will help what you want to do much, as it will take up more storage space, and you want the videos to be temporary and removed as soon as possible.

**Comment by jaruba** [comment]
You can avoid transcoding altogether btw, by using the "Download Playlist" option and playing with your local video player. It works on all devices.

**Comment by odmivolsi** [comment]
Thanks a lot man

**Comment by jaruba** [comment]
I'm closing this issue as it was just a question.
