### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by tejas-16** [jaruba/PowderWeb#67]
It's was showing Application Error and after that they suspended my app??

**Comment by jaruba** [comment]
You are not giving me enough information, who suspended ur app? Is it Heroku? If so then it is not surprising because they have a way to automatically know if an app is using P2P (torrents), and running apps that use P2P technologies is against their Terms and Conditions. I know many others that got their apps suspended on Heroku for trying to use many different torrent related projects.

**Comment by jaruba** [comment]
I'm going to presume that this was about Heroku and point you to the other issue regarding deploying on Heroku: https://github.com/jaruba/PowderWeb/issues/63
